export const TABLES = /** @type {const} */ (["items", "inventory", "rpg_transactions"]);

/**
 * @type {{ [k in typeof TABLES[number]]: { CREATE?: string } }}
 */
export const TABLES_METADATA = {
    "items": {
        "CREATE":
            `
            CREATE TABLE items (
                item_id TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT now(),

                CONSTRAINT item_pkey primary key (item_id),
                -- 限制只能有小寫字母和底線，且長度在 1 到 100 個字元之間
                CONSTRAINT chk_item_id_format
                    CHECK (item_id ~ '^[a-z_]+$' AND length(item_id) <= 100),
                )
            );
            `,
    },
    "inventory": {
        "CREATE":
            `
            CREATE TABLE inventory (
                user_id BIGINT generated by default as identity NOT NULL,
                item_id TEXT NOT NULL,
                amount BIGINT NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

                CONSTRAINT inventory_pkey primary key (user_id, item_id),
                CONSTRAINT inventory_item_id_fkey foreign KEY (item_id)
                    REFERENCES items (item_id) ON DELETE RESTRICT
            );
            `,
    },
    "rpg_transactions": {
        "CREATE":
            `
            CREATE TABLE rpg_transactions (
                id BIGSERIAL PRIMARY KEY,
                timestamp TIMESTAMPTZ NOT NULL,
                original_user BIGINT NOT NULL,
                target_user BIGINT NOT NULL,
                type TEXT NOT NULL,
                -- amount NUMERIC(15, 4) NOT NULL
                amount DOUBLE PRECISION NOT NULL
            );

            -- 建立索引以優化常見的查詢情境
            CREATE INDEX idx_transactions_users ON rpg_transactions (original_user, target_user);
            CREATE INDEX idx_transactions_timestamp ON rpg_transactions (timestamp DESC);
            `,
    }
};
