name: Check Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1 https://github.com/actions/checkout/commit/f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Set up Node.js
        uses: actions/setup-node@94196ee1d15439c1b6651cd87ef14e88ec435966 # v7.0.0 https://github.com/actions/setup-node/commit/94196ee1d15439c1b6651cd87ef14e88ec435966
        with:
          node-version: "24"

      - name: Install Git Secrets
        run: |
          sudo apt-get install git-secrets

      - name: Scan for secrets
        run: |
          git secrets --scan
